#!/bin/bash
# Auto-generated by launch_experiment_var.py
# SV_TYPE=DEL  COVERAGE=10  SV_FREQ=0.9  N_SAMPLES=231
# ERROR_RATE=0.001  K=31  POS=25307000  POS_LABEL=rep3

WORK=/home/tbellagio/scratch/visor_freqk
REF=${WORK}/data/reference/Chr1.fa
VCF_FILE=${WORK}/data/reference/greneNet_final_v1.1.recode.vcf.gz
CHROM_MAP=${WORK}/data/reference/chrom_map.txt
RENAMED_VCF=${WORK}/data/reference/greneNet_final_v1.1.recode.Chr1.vcf.gz

SV_TYPE="DEL"
CHROM="Chr1"
SV_START_0=25307000
ANCHOR_POS=25306999
POS_LABEL="rep3"

N_SAMPLES=231
SV_FREQ=0.9

declare -A DEL_SIZES=(
  ["1kb"]=1000
)

COVERAGE=10
ERROR_RATE=0.001
FREQ=${SV_FREQ}

K=31
FREQK=/home/tbellagio/scratch/pang/test_freqk/freqk/target/release/freqk

HAPS_WT=${WORK}/data/haplotypes_var/wt/n231
HAPS_SV=${WORK}/data/haplotypes_var/del/${POS_LABEL}
BEDS=${WORK}/data/beds/del/${POS_LABEL}
READS_VAR=${WORK}/data/reads_var/del/${POS_LABEL}
READS=${READS_VAR}
VCF_DIR=${WORK}/data/vcf/del/${POS_LABEL}/var
RESULTS=${WORK}/results/del/${POS_LABEL}/var
