#!/bin/bash
# Auto-generated by launch_experiment_var.py
# SV_TYPE=DEL  COVERAGE=50  SV_FREQ=0.7  N_SAMPLES=231
# ERROR_RATE=0.001  K=31  POS=15000000  POS_LABEL=pos15mb

# Common paths
WORK=/home/tbellagio/scratch/visor_freqk
REF=${WORK}/data/reference/Chr1.fa

# GrENET VCF (SNPs only)
VCF_FILE=${WORK}/data/reference/greneNet_final_v1.1.recode.vcf.gz
CHROM_MAP=${WORK}/data/reference/chrom_map.txt
RENAMED_VCF=${WORK}/data/reference/greneNet_final_v1.1.recode.Chr1.vcf.gz

# SV design
SV_TYPE="DEL"
CHROM="Chr1"
SV_START_0=15000000      # BED 0-based start
ANCHOR_POS=14999999       # one base before deletion (VCF POS, 1-based)
POS_LABEL="pos15mb"

# Ecotype panel design
N_SAMPLES=231
SV_FREQ=0.7

declare -A DEL_SIZES=(
  ["100bp"]=100
  ["500bp"]=500
  ["1kb"]=1000
  ["5kb"]=5000
  ["10kb"]=10000
)

# Pool-seq design
COVERAGE=50
ERROR_RATE=0.001
FREQ=${SV_FREQ}

# freqk
K=31
FREQK=/home/tbellagio/scratch/pang/test_freqk/freqk/target/release/freqk

# Directories
HAPS_VAR=${WORK}/data/haplotypes_var/del/${POS_LABEL}
BEDS=${WORK}/data/beds/del/${POS_LABEL}
READS_VAR=${WORK}/data/reads_var/del/${POS_LABEL}
READS=${READS_VAR}
VCF_DIR=${WORK}/data/vcf/del/${POS_LABEL}/var
RESULTS=${WORK}/results/del/${POS_LABEL}/var
