#!/bin/bash
# Auto-generated by launch_experiment.py
# SV_TYPE=DEL  COVERAGE=50  FREQ=0.7  ERROR_RATE=0.001  K=31

WORK=/home/tbellagio/scratch/pang/visor_freqk
REF=${WORK}/data/reference/Chr1.fa
BEDS=${WORK}/data/beds/del/pos10mb
HAPS=${WORK}/data/haplotypes/del/pos10mb
READS=${WORK}/data/reads/del/pos10mb
VCF_DIR=${WORK}/data/vcf/del/pos10mb
RESULTS=${WORK}/results/del/pos10mb

SV_TYPE="DEL"
CHROM="Chr1"
SV_START_0=10000000      # BED 0-based start
POS_LABEL="pos10mb"
ANCHOR_POS=9999999       # one base before deletion (VCF POS, 1-based)

declare -A DEL_SIZES=(
  ["100bp"]=100
  ["500bp"]=500
  ["1kb"]=1000
  ["5kb"]=5000
  ["10kb"]=10000
)

# Pool-seq design
FREQ=0.7
COVERAGE=50
ERROR_RATE=0.001
WT_CLONE=${WORK}/data/haplotypes/del/_clone_WT

# freqk
K=31
FREQK=/home/tbellagio/scratch/pang/test_freqk/freqk/target/release/freqk
