#!/bin/bash
# Auto-generated by launch_experiment.py
# SV_TYPE=INS  COVERAGE=10  FREQ=0.1  ERROR_RATE=0.001  K=31

WORK=/home/tbellagio/scratch/pang/visor_freqk
REF=${WORK}/data/reference/Chr1.fa
BEDS=${WORK}/data/beds/ins
HAPS=${WORK}/data/haplotypes/ins
READS=${WORK}/data/reads/ins
VCF_DIR=${WORK}/data/vcf/ins
RESULTS=${WORK}/results/ins

SV_TYPE="INS"
CHROM="Chr1"
SV_START_0=10000000      # BED 0-based start

declare -A INS_SIZES=(
  ["100bp"]=100
  ["500bp"]=500
  ["1kb"]=1000
  ["5kb"]=5000
  ["10kb"]=10000
)

# Pool-seq design
FREQ=0.1
COVERAGE=10
ERROR_RATE=0.001
WT_CLONE=${HAPS}/_clone_WT

# freqk
K=31
FREQK=/home/tbellagio/scratch/pang/test_freqk/freqk/target/release/freqk
