#!/bin/bash
# Auto-generated by launch_experiment.py
# SV_TYPE=INS  COVERAGE=20  FREQ=0.7  ERROR_RATE=0.001  K=31

WORK=/home/tbellagio/scratch/pang/visor_freqk
REF=${WORK}/data/reference/Chr1.fa
BEDS=${WORK}/data/beds/ins/pos20mb
HAPS=${WORK}/data/haplotypes/ins/pos20mb
READS=${WORK}/data/reads/ins/pos20mb
VCF_DIR=${WORK}/data/vcf/ins/pos20mb
RESULTS=${WORK}/results/ins/pos20mb

SV_TYPE="INS"
CHROM="Chr1"
SV_START_0=20000000      # BED 0-based start
POS_LABEL="pos20mb"

declare -A INS_SIZES=(
  ["100bp"]=100
  ["500bp"]=500
  ["1kb"]=1000
  ["5kb"]=5000
  ["10kb"]=10000
)

# Pool-seq design
FREQ=0.7
COVERAGE=20
ERROR_RATE=0.001
WT_CLONE=${WORK}/data/haplotypes/ins/_clone_WT

# freqk
K=31
FREQK=/home/tbellagio/scratch/pang/test_freqk/freqk/target/release/freqk
