#!/usr/bin/env python3
"""
launch_freqk_runtime_backfill.py
================================
Re-run step 05 (freqk) with FORCE_RUNTIME=1 on combos whose AF TSV exists but
whose `*.runtimes.k<K>.tsv` is missing.  Used to backfill per-step timing for
combos that ran before the runtime instrumentation landed.

Each job re-runs the freqk index/dedup/count/call pipeline on existing reads
and writes a runtime TSV alongside the (already-correct) AF TSV.  Submits one
SLURM job per (rep × cov × freq), each iterating over the requested sizes.

Usage
-----
  # Dry-run (default): print what would be submitted, do not sbatch
  python scripts/launch_freqk_runtime_backfill.py --rep-ids rep1 \\
      --coverage 10 20 50 --sv-freq 0.10 0.30 0.50 0.70 0.90 --n-samples 231

  # Actually submit
  python scripts/launch_freqk_runtime_backfill.py --rep-ids rep1 \\
      --coverage 10 20 50 --sv-freq 0.10 0.30 0.50 0.70 0.90 --n-samples 231 \\
      --submit

The launcher skips combos that already have a runtime TSV on disk.
"""

import argparse
import csv
import datetime
import itertools
import subprocess
import sys
import time
from pathlib import Path

WORK     = "/home/tbellagio/scratch/visor_freqk"
FREQK    = "/home/tbellagio/scratch/bin/freqk"
REGISTRY = Path(WORK) / "data/positions_registry.tsv"

ALL_DEL_SIZES = {"100bp": 100, "500bp": 500, "1kb": 1000, "5kb": 5000, "10kb": 10000}


def _load_registry() -> dict:
    if not REGISTRY.exists() or REGISTRY.stat().st_size == 0:
        sys.exit(f"ERROR: positions_registry.tsv not found at {REGISTRY}")
    with open(REGISTRY) as f:
        return {row["rep_id"]: int(row["pos_bp"])
                for row in csv.DictReader(f, delimiter="\t")}


def _err_label(error_rate: float) -> str:
    if error_rate == 0.0:
        return "0"
    s = f"{error_rate}"
    return s.split(".")[1] if "." in s else s


def _result_dir(pos_label, cov, err_lbl, size, n, freq_lbl, k):
    return (Path(WORK) / "results/del" / pos_label / "var" /
            f"cov{cov}_err{err_lbl}" / size / f"n{n}" / f"f{freq_lbl}" / f"k{k}")


def _af_path(base, size, n, freq_lbl, err_lbl, k):
    return base / f"var_del_{size}_n{n}_f{freq_lbl}_err{err_lbl}.allele_frequencies.k{k}.tsv"


def _runtime_path(base, size, n, freq_lbl, err_lbl, k):
    return base / f"var_del_{size}_n{n}_f{freq_lbl}_err{err_lbl}.runtimes.k{k}.tsv"


def _sizes_needing_backfill(pos_label, cov, err_lbl, n, freq_lbl, k, sizes):
    """Return the subset of `sizes` for this combo that have AF but no runtime TSV."""
    out = []
    for sz in sizes:
        base = _result_dir(pos_label, cov, err_lbl, sz, n, freq_lbl, k)
        if _af_path(base, sz, n, freq_lbl, err_lbl, k).exists() \
           and not _runtime_path(base, sz, n, freq_lbl, err_lbl, k).exists():
            out.append(sz)
    return out


def generate_config(sv_type, coverage, sv_freq, n_samples, error_rate, k,
                    pos, pos_label, sizes):
    sv = sv_type.lower()
    size_lines = "\n".join(f'  ["{name}"]={val}' for name, val in sizes.items())
    anchor_pos = pos - 1
    return f"""\
#!/bin/bash
# Auto-generated by launch_freqk_runtime_backfill.py

WORK={WORK}
REF=${{WORK}}/data/reference/Chr1.fa
VCF_FILE=${{WORK}}/data/reference/greneNet_final_v1.1.recode.vcf.gz
CHROM_MAP=${{WORK}}/data/reference/chrom_map.txt
RENAMED_VCF=${{WORK}}/data/reference/greneNet_final_v1.1.recode.Chr1.vcf.gz

SV_TYPE="{sv_type}"
CHROM="Chr1"
SV_START_0={pos}
ANCHOR_POS={anchor_pos}
POS_LABEL="{pos_label}"

N_SAMPLES={n_samples}
SV_FREQ={sv_freq}

declare -A DEL_SIZES=(
{size_lines}
)

COVERAGE={coverage}
ERROR_RATE={error_rate}
FREQ=${{SV_FREQ}}

K={k}
FREQK={FREQK}

HAPS_WT=${{WORK}}/data/haplotypes_var/wt/n{n_samples}
HAPS_SV=${{WORK}}/data/haplotypes_var/{sv}/${{POS_LABEL}}
BEDS=${{WORK}}/data/beds/{sv}/${{POS_LABEL}}
READS_VAR=${{WORK}}/data/reads_var/{sv}/${{POS_LABEL}}
READS=${{READS_VAR}}
VCF_DIR=${{WORK}}/data/vcf/{sv}/${{POS_LABEL}}/var
RESULTS=${{WORK}}/results/{sv}/${{POS_LABEL}}/var
"""


def main():
    p = argparse.ArgumentParser(formatter_class=argparse.RawDescriptionHelpFormatter,
                                epilog=__doc__)
    p.add_argument("--sv-type",     default="DEL", choices=["DEL"])
    p.add_argument("--coverage",    required=True, type=int,   nargs="+")
    p.add_argument("--sv-freq",     required=True, type=float, nargs="+")
    p.add_argument("--n-samples",   required=True, type=int)
    p.add_argument("--sizes",       nargs="+", default=list(ALL_DEL_SIZES),
                   choices=list(ALL_DEL_SIZES))
    p.add_argument("--rep-ids",     nargs="+",
                   help="reps to backfill (default: all reps in the registry)")
    p.add_argument("--error-rate",  default=0.001, type=float)
    p.add_argument("--k",           default=31, type=int)
    p.add_argument("--stagger-secs", default=2, type=int)
    p.add_argument("--submit",      action="store_true",
                   help="actually sbatch (default is dry-run)")
    args = p.parse_args()

    registry = _load_registry()
    rep_ids  = args.rep_ids or list(registry)
    missing  = [r for r in rep_ids if r not in registry]
    if missing:
        sys.exit(f"ERROR: rep_id(s) not in registry: {', '.join(missing)}")

    err_lbl     = _err_label(args.error_rate)
    scripts_dir = Path(__file__).parent
    config_dir  = scripts_dir / "generated_configs"
    config_dir.mkdir(exist_ok=True)
    step_05     = scripts_dir / "05_freqk_var.sh"
    if not step_05.exists():
        sys.exit(f"ERROR: {step_05} not found")

    combos = sorted(itertools.product(args.coverage, args.sv_freq, rep_ids),
                    key=lambda x: (x[2], x[0], x[1]))

    submitted = skipped = 0
    total_size_jobs = 0
    jobids = []
    ts = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")

    print(f"\nfreqk runtime backfill — submitting (FORCE_RUNTIME=1)")
    print(f"  Reps      : {rep_ids}")
    print(f"  Coverages : {args.coverage}")
    print(f"  SV freqs  : {args.sv_freq}")
    print(f"  Sizes     : {args.sizes}")
    print(f"  Mode      : {'SUBMIT' if args.submit else 'dry-run'}\n")

    for i, (cov, freq, rep_id) in enumerate(combos, 1):
        pos        = registry[rep_id]
        freq_label = int(round(freq * 100))

        sizes_to_run = _sizes_needing_backfill(
            rep_id, cov, err_lbl, args.n_samples, freq_label, args.k, args.sizes,
        )
        if not sizes_to_run:
            skipped += 1
            continue

        sizes_dict = {sz: ALL_DEL_SIZES[sz] for sz in sizes_to_run}
        config_text = generate_config(
            args.sv_type, cov, freq, args.n_samples, args.error_rate,
            args.k, pos, rep_id, sizes_dict,
        )
        config_name = (f"config_var_{args.sv_type.lower()}"
                       f"_n{args.n_samples}_f{freq_label}_cov{cov}"
                       f"_err{err_lbl}_k{args.k}_{rep_id}_rtbackfill.sh")
        config_path = config_dir / config_name
        config_path.write_text(config_text)
        config_path.chmod(0o644)

        cmd = ["sbatch", "--parsable",
               "--export=ALL,FORCE_RUNTIME=1",
               str(step_05), str(config_path)]

        print(f"[{i}/{len(combos)}] {rep_id}  cov={cov}  freq={freq}  "
              f"sizes={','.join(sizes_to_run)}")
        print(f"           submit : {' '.join(cmd)}")

        if not args.submit:
            print(f"           [dry-run]\n")
            total_size_jobs += len(sizes_to_run)
            continue

        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode != 0:
            print(f"           ERROR: {result.stderr.strip()}")
            continue
        jobid = result.stdout.strip()
        jobids.append((rep_id, cov, freq_label, jobid))
        print(f"           job id : {jobid}\n")
        submitted += 1
        total_size_jobs += len(sizes_to_run)

        if i < len(combos) and args.stagger_secs > 0:
            time.sleep(args.stagger_secs)

    if jobids:
        outpath = Path(WORK) / f"logs/freqk_rt_backfill_{ts}.jobids"
        outpath.parent.mkdir(parents=True, exist_ok=True)
        with open(outpath, "w") as f:
            f.write(f"SUBMIT_TS={ts}\n")
            for rep_id, cov, fl, jid in jobids:
                f.write(f"{rep_id}_cov{cov}_f{fl}_05_freqk_rtbackfill={jid}\n")
        print(f"\nJob IDs saved to {outpath}")

    print(f"\nSubmitted: {submitted} jobs covering {total_size_jobs} (rep,cov,freq,size) backfills")
    print(f"Skipped (already have runtime TSV): {skipped}")


if __name__ == "__main__":
    main()
